schema: spec-driven

# Project context (optional)
# This is shown to AI when creating artifacts.
# Add your tech stack, conventions, style guides, domain knowledge, etc.
# Example:
context: |
  Tech stack: go
  We use conventional commits
  Domain: blob storage synchronization
  Style guide and conventions: clean code (SOLID, DRY, YAGNI), DDD and TDD (new features *must* be implemented with a test driven development approach)
  Language: Italian for chat messages, English for anything else
  GIT: each new feature must be implemented in a separate feature branch ('feature/name-of-feature'). Make a commit for every milestone reached during the implementation.
  Agents: DO NOT use subagents, ALWAYS use the main running agent.

# Per-artifact rules (optional)
# Add custom rules for specific artifacts.
rules:
  tasks:
    - The VERY FIRST task in group 1 MUST be to create and checkout the feature branch (`feature/<kebab-case-name>`).
    - Every heading (`##`) represents a Milestone.
    - Every milestone composed of implementation tasks MUST start with tests, in accordance to TDD principles.
    - The VERY LAST task in EVERY Milestone group MUST be a git commit command to save the progress of that milestone.
  
